versions![
    (0, "r/0_u0", "0.0.0"): {
        raknet_version: 10,
        packets: [
            + RequestNetworkSettingsPacket: RequestNetworkSettingsPacket,
        ] in crate::version::unknown::packets,
    } as Unknown,
    (662, "r/20_u7", "1.20.70"): {
        raknet_version: 11,
        packets: [
            + ActorEventPacket: ActorEventPacket^,
            + ActorPickRequestPacket: ActorPickRequestPacket,
            + AddActorPacket: AddActorPacket^,
            + AddBehaviourTreePacket: AddBehaviourTreePacket,
            + AddItemActorPacket: AddItemActorPacket^,
            + AddPaintingPacket: AddPaintingPacket^,
            + AddPlayerPacket: AddPlayerPacket^,
            + AddVolumeEntityPacket: AddVolumeEntityPacket^,
            + AgentActionEventPacket: AgentActionEventPacket^,
            + AgentAnimationPacket: AgentAnimationPacket^,
            + AnimateEntityPacket: AnimateEntityPacket^,
            + AnimatePacket: AnimatePacket^,
            + AnvilDamagePacket: AnvilDamagePacket^,
            + AutomationClientConnectPacket: AutomationClientConnectPacket^,
            + AvailableActorIdentifiersPacket: AvailableActorIdentifiersPacket,
            + AvailableCommandsPacket: AvailableCommandsPacket^,
            + BiomeDefinitionListPacket: BiomeDefinitionListPacket,
            + BlockActorDataPacket: BlockActorDataPacket^,
            + BlockEventPacket: BlockEventPacket^,
            + BlockPickRequestPacket: BlockPickRequestPacket^,
            + BookEditPacket: BookEditPacket^,
            + BossEventPacket: BossEventPacket^,
            + CameraInstructionPacket: CameraInstructionPacket^,
            + CameraPacket: CameraPacket^,
            + CameraPresetsPacket: CameraPresetsPacket^,
            + CameraShakePacket: CameraShakePacket^,
            + ChangeDimensionPacket: ChangeDimensionPacket,
            + ChangeMobPropertyPacket: ChangeMobPropertyPacket^,
            + ChunkRadiusUpdatedPacket: ChunkRadiusUpdatedPacket,
            + ClientBoundDebugRendererPacket: ClientBoundDebugRendererPacket,
            + ClientBoundMapItemDataPacket: ClientBoundMapItemDataPacket^,
            + ClientCacheBlobStatusPacket: ClientCacheBlobStatusPacket,
            + ClientCacheMissResponsePacket: ClientCacheMissResponsePacket,
            + ClientCacheStatusPacket: ClientCacheStatusPacket,
            + ClientToServerHandshakePacket: ClientToServerHandshakePacket,
            + CodeBuilderPacket: CodeBuilderPacket,
            + CodeBuilderSourcePacket: CodeBuilderSourcePacket^,
            + CommandBlockUpdatePacket: CommandBlockUpdatePacket^,
            + CommandOutputPacket: CommandOutputPacket^,
            + CommandRequestPacket: CommandRequestPacket^,
            + CompletedUsingItemPacket: CompletedUsingItemPacket^,
            + CompressedBiomeDefinitionListPacket: CompressedBiomeDefinitionListPacket,
            + ContainerClosePacket: ContainerClosePacket^,
            + ContainerOpenPacket: ContainerOpenPacket^,
            + ContainerSetDataPacket: ContainerSetDataPacket^,
            + CorrectPlayerMovePredictionPacket: CorrectPlayerMovePredictionPacket^,
            + CraftingDataPacket: CraftingDataPacket^,
            + CreatePhotoPacket: CreatePhotoPacket,
            + CreativeContentPacket: CreativeContentPacket^,
            + DeathInfoPacket: DeathInfoPacket,
            + DebugInfoPacket: DebugInfoPacket^,
            + DimensionDataPacket: DimensionDataPacket^,
            + DisconnectPacket: DisconnectPacket^,
            + EditorNetworkPacket: EditorNetworkPacket,
            + EduUriResourcePacket: EduUriResourcePacket^,
            + EducationSettingsPacket: EducationSettingsPacket^,
            + EmoteListPacket: EmoteListPacket^,
            + EmotePacket: EmotePacket^,
            + FeatureRegistryPacket: FeatureRegistryPacket,
            + FilterTextPacket: FilterTextPacket,
            + GameRulesChangedPacket: GameRulesChangedPacket^,
            + GameTestRequestPacket: GameTestRequestPacket^,
            + GameTestResultsPacket: GameTestResultsPacket,
            + GuiDataPickItemPacket: GuiDataPickItemPacket,
            + HurtArmorPacket: HurtArmorPacket,
            + InteractPacket: InteractPacket^,
            + InventoryContentPacket: InventoryContentPacket^,
            + InventorySlotPacket: InventorySlotPacket^,
            + InventoryTransactionPacket: InventoryTransactionPacket^,
            + ItemComponentPacket: ItemComponentPacket,
            + ItemStackRequestPacket: ItemStackRequestPacket^,
            + ItemStackResponsePacket: ItemStackResponsePacket^,
            + LabTablePacket: LabTablePacket^,
            + LecternUpdatePacket: LecternUpdatePacket^,
            + LegacyTelemetryEventPacket: LegacyTelemetryEventPacket^,
            + LessonProgressPacket: LessonProgressPacket^,
            + LevelChunkPacket: LevelChunkPacket^,
            + LevelEventGenericPacket: LevelEventGenericPacket^,
            + LevelEventPacket: LevelEventPacket,
            + LevelSoundEventPacket: LevelSoundEventPacket^,
            + LevelSoundEventV1Packet: LevelSoundEventV1Packet^,
            + LevelSoundEventV2Packet: LevelSoundEventV2Packet^,
            + LoginPacket: LoginPacket,
            + MapCreateLockedCopyPacket: MapCreateLockedCopyPacket^,
            + MapInfoRequestPacket: MapInfoRequestPacket^,
            + MobArmorEquipmentPacket: MobArmorEquipmentPacket^,
            + MobEffectPacket: MobEffectPacket^,
            + MobEquipmentPacket: MobEquipmentPacket^,
            + ModalFormRequestPacket: ModalFormRequestPacket,
            + ModalFormResponsePacket: ModalFormResponsePacket^,
            + MotionPredictionHintsPacket: MotionPredictionHintsPacket^,
            + MoveActorAbsolutePacket: MoveActorAbsolutePacket^,
            + MoveActorDeltaPacket: MoveActorDeltaPacket^,
            + MovePlayerPacket: MovePlayerPacket^,
            + MultiplayerSettingsPacket: MultiplayerSettingsPacket^,
            + NetworkChunkPublisherUpdatePacket: NetworkChunkPublisherUpdatePacket^,
            + NetworkSettingsPacket: NetworkSettingsPacket^,
            + NetworkStackLatencyPacket: NetworkStackLatencyPacket,
            + NpcDialoguePacket: NpcDialoguePacket,
            + NpcRequestPacket: NpcRequestPacket^,
            + OnScreenTextureAnimationPacket: OnScreenTextureAnimationPacket,
            + OpenSignPacket: OpenSignPacket^,
            + PacketViolationWarningPacket: PacketViolationWarningPacket^,
            + PassengerJumpPacket: PassengerJumpPacket,
            + PhotoTransferPacket: PhotoTransferPacket^,
            + PlaySoundPacket: PlaySoundPacket^,
            + PlayStatusPacket: PlayStatusPacket^,
            + PlayerActionPacket: PlayerActionPacket^,
            + PlayerArmorDamagePacket: PlayerArmorDamagePacket,
            + PlayerAuthInputPacket: PlayerAuthInputPacket^,
            + PlayerEnchantOptionsPacket: PlayerEnchantOptionsPacket^,
            + PlayerFogPacket: PlayerFogPacket,
            + PlayerHotbarPacket: PlayerHotbarPacket^,
            + PlayerInputPacket: PlayerInputPacket,
            + PlayerListPacket: PlayerListPacket^,
            + PlayerSkinPacket: PlayerSkinPacket^,
            + PlayerStartItemCooldownPacket: PlayerStartItemCooldownPacket,
            + PlayerToggleCrafterSlotRequestPacket: PlayerToggleCrafterSlotRequestPacket,
            + PositionTrackingDBClientRequestPacket: PositionTrackingDBClientRequestPacket^,
            + PositionTrackingDBServerBroadcastPacket: PositionTrackingDBServerBroadcastPacket^,
            + PurchaseReceiptPacket: PurchaseReceiptPacket,
            + RefreshEntitlementsPacket: RefreshEntitlementsPacket,
            + RemoveActorPacket: RemoveActorPacket^,
            + RemoveObjectivePacket: RemoveObjectivePacket,
            + RemoveVolumeEntityPacket: RemoveVolumeEntityPacket^,
            + RequestAbilityPacket: RequestAbilityPacket^,
            + RequestChunkRadiusPacket: RequestChunkRadiusPacket,
            + RequestPermissionsPacket: RequestPermissionsPacket^,
            + ResourcePackChunkDataPacket: ResourcePackChunkDataPacket,
            + ResourcePackChunkRequestPacket: ResourcePackChunkRequestPacket,
            + ResourcePackClientResponsePacket: ResourcePackClientResponsePacket^,
            + ResourcePackDataInfoPacket: ResourcePackDataInfoPacket^,
            + ResourcePackStackPacket: ResourcePackStackPacket^,
            + ResourcePacksInfoPacket: ResourcePacksInfoPacket,
            + RespawnPacket: RespawnPacket^,
            + ScriptMessagePacket: ScriptMessagePacket,
            + ServerPlayerPostMovePositionPacket: ServerPlayerPostMovePositionPacket,
            + ServerSettingsRequestPacket: ServerSettingsRequestPacket,
            + ServerSettingsResponsePacket: ServerSettingsResponsePacket,
            + ServerStatsPacket: ServerStatsPacket,
            + ServerToClientHandshakePacket: ServerToClientHandshakePacket,
            + SetActorDataPacket: SetActorDataPacket^,
            + SetActorLinkPacket: SetActorLinkPacket^,
            + SetActorMotionPacket: SetActorMotionPacket^,
            + SetCommandsEnabledPacket: SetCommandsEnabledPacket,
            + SetDefaultGameTypePacket: SetDefaultGameTypePacket^,
            + SetDifficultyPacket: SetDifficultyPacket,
            + SetDisplayObjectivePacket: SetDisplayObjectivePacket^,
            + SetHealthPacket: SetHealthPacket,
            + SetHudPacket: SetHudPacket^,
            + SetLastHurtByPacket: SetLastHurtByPacket^,
            + SetLocalPlayerAsInitializedPacket: SetLocalPlayerAsInitializedPacket^,
            + SetPlayerGameTypePacket: SetPlayerGameTypePacket^,
            + SetPlayerInventoryOptionsPacket: SetPlayerInventoryOptionsPacket^,
            + SetScorePacket: SetScorePacket^,
            + SetScoreboardIdentityPacket: SetScoreboardIdentityPacket^,
            + SetSpawnPositionPacket: SetSpawnPositionPacket^,
            + SetTimePacket: SetTimePacket,
            + SetTitlePacket: SetTitlePacket,
            + SettingsCommandPacket: SettingsCommandPacket,
            + ShowCreditsPacket: ShowCreditsPacket^,
            + ShowProfilePacket: ShowProfilePacket,
            + ShowStoreOfferPacket: ShowStoreOfferPacket^,
            + SimpleEventPacket: SimpleEventPacket,
            + SimulationTypePacket: SimulationTypePacket^,
            + SpawnExperienceOrbPacket: SpawnExperienceOrbPacket,
            + SpawnParticleEffectPacket: SpawnParticleEffectPacket^,
            + StartGamePacket: StartGamePacket^,
            + StopSoundPacket: StopSoundPacket,
            + StructureBlockUpdatePacket: StructureBlockUpdatePacket^,
            + StructureDataRequestPacket: StructureDataRequestPacket^,
            + StructureDataResponsePacket: StructureDataResponsePacket^,
            + SubChunkPacket: SubChunkPacket^,
            + SubChunkRequestPacket: SubChunkRequestPacket^,
            + SubClientLoginPacket: SubClientLoginPacket,
            + SyncActorPropertyPacket: SyncActorPropertyPacket,
            + TakeItemActorPacket: TakeItemActorPacket^,
            + TextPacket: TextPacket^,
            + TickSyncPacket: TickSyncPacket,
            + TickingAreaLoadStatusPacket: TickingAreaLoadStatusPacket,
            + ToastRequestPacket: ToastRequestPacket,
            + TransferPlayerPacket: TransferPlayerPacket,
            + TrimDataPacket: TrimDataPacket,
            + UnlockedRecipesPacket: UnlockedRecipesPacket,
            + UpdateAbilitiesPacket: UpdateAbilitiesPacket^,
            + UpdateAdventureSettingsPacket: UpdateAdventureSettingsPacket^,
            + UpdateAttributesPacket: UpdateAttributesPacket^,
            + UpdateBlockPacket: UpdateBlockPacket^,
            + UpdateBlockSyncedPacket: UpdateBlockSyncedPacket^,
            + UpdateClientInputLocksPacket: UpdateClientInputLocksPacket,
            + UpdateEquipPacket: UpdateEquipPacket^,
            + UpdatePlayerGameTypePacket: UpdatePlayerGameTypePacket^,
            + UpdateSoftEnumPacket: UpdateSoftEnumPacket^,
            + UpdateSubChunkBlocksPacket: UpdateSubChunkBlocksPacket^,
            + UpdateTradePacket: UpdateTradePacket^,
            % RequestNetworkSettingsPacket: RequestNetworkSettingsPacket,
        ] in crate::version::v662::packets,
        types: [
            + ActorLink: ActorLink^,
            + ActorRuntimeID: ActorRuntimeID,
            + ActorUniqueID: ActorUniqueID,
            + AdventureSettings: AdventureSettings,
            + BaseDescription: BaseDescription^,
            + BaseGameVersion: BaseGameVersion,
            + BlockPos: BlockPos,
            + CameraInstruction: CameraInstruction^,
            + CameraPreset: CameraPreset,
            + CameraPresets: CameraPresets^,
            + ChunkPos: ChunkPos,
            + CommandOriginData: CommandOriginData^,
            + ContainerMixDataEntry: ContainerMixDataEntry,
            + CraftingDataEntry: CraftingDataEntry^,
            + DataItem: DataItem^,
            + DimensionDefinitionGroup: DimensionDefinitionGroup,
            + EduSharedUriResource: EduSharedUriResource,
            + EducationLevelSettings: EducationLevelSettings,
            + EntityNetID: EntityNetID,
            + Experiments: Experiments,
            + GameRulesChangedPacketData: GameRulesChangedPacketData,
            + InventoryAction: InventoryAction^,
            + InventorySource: InventorySource^,
            + InventoryTransaction: InventoryTransaction^,
            + ItemData: ItemData,
            + ItemEnchants: ItemEnchants^,
            + ItemStackRequestSlotInfo: ItemStackRequestSlotInfo^,
            + ItemStackResponseContainerInfo: ItemStackResponseContainerInfo^,
            + ItemStackResponseInfo: ItemStackResponseInfo^,
            + ItemStackResponseSlotInfo: ItemStackResponseSlotInfo,
            + LevelSettings: LevelSettings^,
            + MapDecoration: MapDecoration,
            + MapItemTrackedActorUniqueID: MapItemTrackedActorUniqueID^,
            + MaterialReducerDataEntry: MaterialReducerDataEntry,
            + MolangVariableMap: MolangVariableMap,
            + MoveActorAbsoluteData: MoveActorAbsoluteData^,
            + MoveActorDeltaData: MoveActorDeltaData^,
            + NetworkBlockPosition: NetworkBlockPosition,
            + NetworkItemInstanceDescriptor: NetworkItemInstanceDescriptor,
            + NetworkItemStackDescriptor: NetworkItemStackDescriptor,
            + NetworkPermissions: NetworkPermissions,
            + PackedItemUseLegacyInventoryTransaction: PackedItemUseLegacyInventoryTransaction^,
            + PlayerBlockActionData: PlayerBlockActionData^,
            + PositionTrackingId: PositionTrackingId,
            + PotionMixDataEntry: PotionMixDataEntry,
            + PropertySyncData: PropertySyncData,
            + RecipeIngredient: RecipeIngredient^,
            + ScoreboardId: ScoreboardId,
            + SerializedAbilitiesData: SerializedAbilitiesData^,
            + SerializedSkin: SerializedSkin^,
            + ShapedRecipe: ShapedRecipe^,
            + ShapelessRecipe: ShapelessRecipe^,
            + ShulkerBoxRecipe: ShulkerBoxRecipe^,
            + SmithingTransformRecipe: SmithingTransformRecipe^,
            + SmithingTrimRecipe: SmithingTrimRecipe^,
            + SpawnSettings: SpawnSettings^,
            + StructureEditorData: StructureEditorData^,
            + StructureSettings: StructureSettings^,
            + SubChunkPos: SubChunkPos,
            + SubChunkPosOffset: SubChunkPosOffset,
            + SyncedPlayerMovementSettings: SyncedPlayerMovementSettings^,
            + WebSocketPacketData: WebSocketPacketData,
        ] in crate::version::v662::types,
        enums: [
            + AbilitiesIndex: AbilitiesIndex,
            + ActorBlockSyncMessageID: ActorBlockSyncMessageID,
            + ActorDamageCause: ActorDamageCause,
            + ActorDataIDs: ActorDataIDs,
            + ActorEvent: ActorEvent,
            + ActorFlags: ActorFlags,
            + ActorLinkType: ActorLinkType,
            + ActorType: ActorType,
            + AgentActionType: AgentActionType,
            + AnimatedTextureType: AnimatedTextureType,
            + AnimationExpression: AnimationExpression,
            + AnimationMode: AnimationMode,
            + AttributeModifierOperation: AttributeModifierOperation,
            + AttributeOperands: AttributeOperands,
            + BookEditAction: BookEditAction,
            + BossEventUpdateType: BossEventUpdateType^,
            + BuildPlatform: BuildPlatform,
            + CameraShakeAction: CameraShakeAction,
            + CameraShakeType: CameraShakeType,
            + ChatRestrictionLevel: ChatRestrictionLevel,
            + CodeBuilderStorageCategory: CodeBuilderStorageCategory,
            + CodeBuilderStorageOperation: CodeBuilderStorageOperation,
            + CommandBlockMode: CommandBlockMode,
            + CommandOriginType: CommandOriginType,
            + CommandOutputType: CommandOutputType,
            + CommandParameterOption: CommandParameterOption,
            + CommandPermissionLevel: CommandPermissionLevel,
            + ComplexInventoryTransactionType: ComplexInventoryTransactionType,
            + ConnectionFailReason: ConnectionFailReason,
            + ContainerEnumName: ContainerEnumName,
            + ContainerID: ContainerID,
            + ContainerType: ContainerType,
            + CraftingDataEntryType: CraftingDataEntryType^,
            + DataItemType: DataItemType^,
            + Difficulty: Difficulty,
            + EasingType: EasingType,
            + EditorWorldType: EditorWorldType,
            + EducationEditionOffer: EducationEditionOffer,
            + EnchantType: EnchantType,
            + GamePublishSetting: GamePublishSetting,
            + GameType: GameType,
            + GeneratorType: GeneratorType,
            + HudElement: HudElement,
            + HudVisibility: HudVisibility,
            + IdentityDefinitionType: IdentityDefinitionType^,
            + InputMode: InputMode,
            + InteractionType: InteractionType,
            + InventoryLayout: InventoryLayout,
            + InventoryLeftTabIndex: InventoryLeftTabIndex,
            + InventoryRightTabIndex: InventoryRightTabIndex,
            + InventorySourceFlags: InventorySourceFlags,
            + InventorySourceType: InventorySourceType^,
            + ItemDescriptorType: ItemDescriptorType,
            + ItemReleaseInventoryTransactionType: ItemReleaseInventoryTransactionType,
            + ItemStackNetResult: ItemStackNetResult^,
            + ItemStackRequestActionType: ItemStackRequestActionType^,
            + ItemUseInventoryTransactionType: ItemUseInventoryTransactionType,
            + ItemUseMethod: ItemUseMethod,
            + ItemUseOnActorInventoryTransactionType: ItemUseOnActorInventoryTransactionType,
            + LabTableReactionType: LabTableReactionType,
            + LessonAction: LessonAction,
            + LevelEvent: LevelEvent,
            + LevelSoundEventType: LevelSoundEventType,
            + MinecraftPacketIds: MinecraftPacketIds,
            + Mirror: Mirror,
            + ModalFormCancelReason: ModalFormCancelReason,
            + MolangVersion: MolangVersion,
            + MultiplayerSettingsPacketType: MultiplayerSettingsPacketType,
            + NewInteractionModel: NewInteractionModel,
            + ObjectiveSortOrder: ObjectiveSortOrder,
            + POIBlockInteractionType: POIBlockInteractionType,
            + PackType: PackType,
            + PacketCompressionAlgorithm: PacketCompressionAlgorithm,
            + PacketViolationSeverity: PacketViolationSeverity,
            + PacketViolationType: PacketViolationType,
            + ParticleType: ParticleType,
            + PhotoType: PhotoType,
            + PlayStatus: PlayStatus,
            + PlayerPermissionLevel: PlayerPermissionLevel,
            + PlayerPositionMode: PlayerPositionMode,
            + PlayerRespawnState: PlayerRespawnState,
            + PredictionType: PredictionType,
            + ResourcePackResponse: ResourcePackResponse,
            + Rotation: Rotation,
            + ServerAuthMovementMode: ServerAuthMovementMode,
            + ShowStoreOfferRedirectType: ShowStoreOfferRedirectType,
            + SimulationType: SimulationType,
            + SoftEnumUpdateType: SoftEnumUpdateType,
            + SpawnBiomeType: SpawnBiomeType,
            + SpawnPositionType: SpawnPositionType,
            + StructureBlockType: StructureBlockType,
            + StructureRedstoneSaveMode: StructureRedstoneSaveMode,
            + StructureTemplateRequestOperation: StructureTemplateRequestOperation,
            + StructureTemplateResponseType: StructureTemplateResponseType,
            + TeleportationCause: TeleportationCause,
            + TextPacketType: TextPacketType,
            + TextProcessingEventOrigin: TextProcessingEventOrigin,
            + UIProfile: UIProfile,
        ] in crate::version::v662::enums,
    },
    (671, "r/20_u8", "1.20.80"): {
        packets: [
            % ClientBoundDebugRendererPacket: ClientBoundDebugRendererPacket,
            % CorrectPlayerMovePredictionPacket: CorrectPlayerMovePredictionPacket^,
            % LegacyTelemetryEventPacket: LegacyTelemetryEventPacket^,
            % ResourcePackStackPacket: ResourcePackStackPacket^,
            % UpdatePlayerGameTypePacket: UpdatePlayerGameTypePacket^,
            - FilterTextPacket,
        ] in crate::version::v671::packets,
        types: [
            % LevelSettings: LevelSettings^,
            % ShapedRecipe: ShapedRecipe^,
        ] in crate::version::v671::types,
        enums: [
            % ActorFlags: ActorFlags,
            % LevelSoundEventType: LevelSoundEventType,
            % ParticleType: ParticleType,
            % PredictionType: PredictionType,
        ] in crate::version::v671::enums,
    },
    (685, "r/21_u0", "1.21.0"): {
        packets: [
            + AwardAchievementPacket: AwardAchievementPacket,
            % CodeBuilderSourcePacket: CodeBuilderSourcePacket^,
            % ContainerClosePacket: ContainerClosePacket^,
            % LegacyTelemetryEventPacket: LegacyTelemetryEventPacket^,
            % TextPacket: TextPacket^,
            - TickSyncPacket,
        ] in crate::version::v685::packets,
        types: [
            + RecipeUnlockingRequirement: RecipeUnlockingRequirement^,
            % LevelSettings: LevelSettings^,
            % ShapedRecipe: ShapedRecipe^,
            % ShapelessRecipe: ShapelessRecipe^,
        ] in crate::version::v685::types,
        enums: [
            + CodeBuilderCodeStatus: CodeBuilderCodeStatus,
            % ActorDataIDs: ActorDataIDs,
            % LevelEvent: LevelEvent,
            % LevelSoundEventType: LevelSoundEventType,
            % ParticleType: ParticleType,
        ] in crate::version::v685::enums,
    },
    (686, "r/21_u0", "1.21.2"): {
        packets: [
            + ClientBoundCloseFormPacket: ClientBoundCloseFormPacket,
        ] in crate::version::v686::packets,
    },
    (712, "r/21_u2", "1.21.20"): {
        packets: [
            + CurrentStructureFeaturePacket: CurrentStructureFeaturePacket,
            + JigsawStructureDataPacket: JigsawStructureDataPacket,
            + ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            + ServerBoundLoadingScreenPacket: ServerBoundLoadingScreenPacket,
            % CameraInstructionPacket: CameraInstructionPacket^,
            % ChangeDimensionPacket: ChangeDimensionPacket,
            % DisconnectPacket: DisconnectPacket^,
            % InventoryContentPacket: InventoryContentPacket^,
            % InventorySlotPacket: InventorySlotPacket^,
            % MobArmorEquipmentPacket: MobArmorEquipmentPacket^,
            % PlayerArmorDamagePacket: PlayerArmorDamagePacket,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
            % SetTitlePacket: SetTitlePacket,
            % StopSoundPacket: StopSoundPacket,
        ] in crate::version::v712::packets,
        types: [
            + FullContainerName: FullContainerName^,
            % ActorLink: ActorLink^,
            % CameraInstruction: CameraInstruction^,
            % CameraPreset: CameraPreset,
            % ItemStackRequestSlotInfo: ItemStackRequestSlotInfo^,
            % ItemStackResponseContainerInfo: ItemStackResponseContainerInfo^,
            % PackedItemUseLegacyInventoryTransaction: PackedItemUseLegacyInventoryTransaction^,
        ] in crate::version::v712::types,
        enums: [
            % ContainerEnumName: ContainerEnumName,
            % ItemStackRequestActionType: ItemStackRequestActionType^,
            % LevelSoundEventType: LevelSoundEventType,
            % PredictionType: PredictionType,
        ] in crate::version::v712::enums,
    },
    (729, "r/21_u3", "1.21.30"): {
        packets: [
            + CameraAimAssistPacket: CameraAimAssistPacket^,
            + ContainerRegistryCleanupPacket: ContainerRegistryCleanupPacket^,
            % EmotePacket: EmotePacket^,
            % InventoryContentPacket: InventoryContentPacket^,
            % InventorySlotPacket: InventorySlotPacket^,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
            % TransferPlayerPacket: TransferPlayerPacket,
            % UpdateAttributesPacket: UpdateAttributesPacket^,
        ] in crate::version::v729::packets,
        types: [
            % CameraPreset: CameraPreset,
            % FullContainerName: FullContainerName^,
        ] in crate::version::v729::types,
        enums: [
            + AimAssistAction: AimAssistAction,
            % LevelSoundEventType: LevelSoundEventType,
        ] in crate::version::v729::enums,
    },
    (748, "r/21_u4", "1.21.40"): {
        packets: [
            + MovementEffectPacket: MovementEffectPacket^,
            + SetMovementAuthorityPacket: SetMovementAuthorityPacket^,
            % InventoryContentPacket: InventoryContentPacket^,
            % InventorySlotPacket: InventorySlotPacket^,
            % MobEffectPacket: MobEffectPacket^,
            % PlayerAuthInputPacket: PlayerAuthInputPacket^,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
        ] in crate::version::v748::packets,
        types: [
            % CameraInstruction: CameraInstruction^,
            % CameraPreset: CameraPreset,
            % ShulkerBoxRecipe: ShulkerBoxRecipe^,
        ] in crate::version::v748::types,
        enums: [
            + AuthoritativeMovementMode: AuthoritativeMovementMode,
            + MovementEffectType: MovementEffectType,
        ] in crate::version::v748::enums,
    },
    (766, "r/21_u5", "1.21.50"): {
        packets: [
            + CameraAimAssistPresetsPacket: CameraAimAssistPresetsPacket^,
            % CameraAimAssistPacket: CameraAimAssistPacket^,
            % PlayerAuthInputPacket: PlayerAuthInputPacket^,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
        ] in crate::version::v766::packets,
        types: [
            + CameraAimAssistCategories: CameraAimAssistCategories^,
            + CameraAimAssistCategory: CameraAimAssistCategory^,
            + CameraAimAssistItemSettings: CameraAimAssistItemSettings,
            + CameraAimAssistPreset: CameraAimAssistPreset,
            + CameraAimAssistPresetDefinition: CameraAimAssistPresetDefinition^,
            + CameraAimAssistPriority: CameraAimAssistPriority,
            % CameraPreset: CameraPreset^,
            % ItemStackResponseSlotInfo: ItemStackResponseSlotInfo,
        ] in crate::version::v766::types,
        enums: [
            % LevelEvent: LevelEvent,
            % LevelSoundEventType: LevelSoundEventType,
            % ParticleType: ParticleType,
        ] in crate::version::v766::enums,
    },
    (776, "r/21_u6", "1.21.60"): {
        packets: [
            + CameraAimAssistInstructionPacket: CameraAimAssistInstructionPacket^,
            + MovementPredictionSyncPacket: MovementPredictionSyncPacket^,
            % CameraAimAssistPresetsPacket: CameraAimAssistPresetsPacket^,
            % CommandBlockUpdatePacket: CommandBlockUpdatePacket^,
            % CreativeContentPacket: CreativeContentPacket^,
            % ItemComponentPacket: ItemComponentPacket^,
            % StartGamePacket: StartGamePacket^,
        ] in crate::version::v776::packets,
        types: [
            % CameraAimAssistPresetDefinition: CameraAimAssistPresetDefinition^,
            % CameraPreset: CameraPreset^,
            % SerializedAbilitiesData: SerializedAbilitiesData^,
            % StructureEditorData: StructureEditorData^,
        ] in crate::version::v776::types,
        enums: [
            + CameraAimAssistOperation: CameraAimAssistOperation,
            + ItemVersion: ItemVersion,
            % AbilitiesIndex: AbilitiesIndex,
            % ActorDataIDs: ActorDataIDs,
            % ActorFlags: ActorFlags,
            % BossEventUpdateType: BossEventUpdateType^,
        ] in crate::version::v776::enums,
    },
    (786, "r/21_u7", "1.21.70"): {
        packets: [
            + PlayerUpdateEntityOverridesPacket: PlayerUpdateEntityOverridesPacket^,
            + PlayerVideoCapturePacket: PlayerVideoCapturePacket,
            + UpdateClientOptionsPacket: UpdateClientOptionsPacket,
            % LevelSoundEventPacket: LevelSoundEventPacket^,
            % MovementPredictionSyncPacket: MovementPredictionSyncPacket^,
            - LevelSoundEventV1Packet,
            - LevelSoundEventV2Packet,
        ] in crate::version::v786::packets,
        enums: [
            % ActorFlags: ActorFlags,
            % HudElement: HudElement,
            % HudVisibility: HudVisibility,
        ] in crate::version::v786::enums,
    },
    (800, "r/21_u8", "1.21.80"): {
        packets: [
            + ClientBoundControlSchemeSetPacket: ClientBoundControlSchemeSetPacket^,
            + PlayerLocationPacket: PlayerLocationPacket,
            % BiomeDefinitionListPacket: BiomeDefinitionListPacket^,
            % CameraAimAssistPresetsPacket: CameraAimAssistPresetsPacket^,
            % PlayerListPacket: PlayerListPacket^,
            - CompressedBiomeDefinitionListPacket,
            - PlayerInputPacket,
            - PassengerJumpPacket,
        ] in crate::version::v800::packets,
        types: [
            + BiomeCappedSurfaceData: BiomeCappedSurfaceData,
            + BiomeClimateData: BiomeClimateData,
            + BiomeConditionalTransformationData: BiomeConditionalTransformationData^,
            + BiomeConsolidatedFeatureList: BiomeConsolidatedFeatureList^,
            + BiomeCoordinateData: BiomeCoordinateData,
            + BiomeDefinition: BiomeDefinition^,
            + BiomeDefinitionChunkGenData: BiomeDefinitionChunkGenData^,
            + BiomeElementData: BiomeElementData^,
            + BiomeLegacyWorldGenRulesData: BiomeLegacyWorldGenRulesData^,
            + BiomeMesaSurfaceData: BiomeMesaSurfaceData,
            + BiomeMountainParamsData: BiomeMountainParamsData,
            + BiomeMultinoiseGenRulesData: BiomeMultinoiseGenRulesData,
            + BiomeOverworldGenRulesData: BiomeOverworldGenRulesData^,
            + BiomeScatterParamData: BiomeScatterParamData^,
            + BiomeSurfaceMaterialAdjustmentData: BiomeSurfaceMaterialAdjustmentData^,
            + BiomeSurfaceMaterialData: BiomeSurfaceMaterialData,
            + BiomeWeightedData: BiomeWeightedData,
            + BiomeWeightedTemperatureData: BiomeWeightedTemperatureData,
            + Color: Color,
            % CameraPreset: CameraPreset^,
        ] in crate::version::v800::types,
        enums: [
            + ControlScheme: ControlScheme,
            % ActorDataIDs: ActorDataIDs,
            % ActorFlags: ActorFlags,
            % LevelSoundEventType: LevelSoundEventType,
        ] in crate::version::v800::enums,
    },
    (818, "r/21_u9", "1.21.90"): {
        packets: [
            + DebugDrawerPacket: DebugDrawerPacket^,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
            % SubChunkPacket: SubChunkPacket^,
            - SetMovementAuthorityPacket,
        ] in crate::version::v818::packets,
        types: [
            + DebugShape: DebugShape^,
            % CameraInstruction: CameraInstruction^,
            % CameraPreset: CameraPreset^,
            % LevelSettings: LevelSettings^,
            % SyncedPlayerMovementSettings: SyncedPlayerMovementSettings,
        ] in crate::version::v818::types,
        enums: [
            % ActorFlags: ActorFlags,
            % LevelSoundEventType: LevelSoundEventType,
            - ServerAuthMovementMode,
        ] in crate::version::v818::enums,
    },
    (819, "r/21_u9", "1.21.93"): {
        enums: [
            % LevelSoundEventType: LevelSoundEventType,
        ] in crate::version::v819::enums,
    },
    (827, "r/21_u10", "1.21.100"): {
        packets: [
            % CameraAimAssistPacket: CameraAimAssistPacket^,
            % CorrectPlayerMovePredictionPacket: CorrectPlayerMovePredictionPacket^,
            % StartGamePacket: StartGamePacket^,
        ] in crate::version::v827::packets,
        types: [
            % BiomeDefinition: BiomeDefinition^,
            % CameraInstruction: CameraInstruction^,
        ] in crate::version::v827::types,
        enums: [
            % LevelSoundEventType: LevelSoundEventType,
            % PredictionType: PredictionType,
        ] in crate::version::v827::enums,
    },
    (844, "r/21_u11", "1.21.111"): {
        packets: [
            + ServerBoundPackSettingChangePacket: ServerBoundPackSettingChangePacket,
            % PlayerArmorDamagePacket: PlayerArmorDamagePacket,
        ] in crate::version::v844::packets,
        types: [
            % BiomeClimateData: BiomeClimateData,
            % BiomeDefinition: BiomeDefinition^,
            % BiomeDefinitionChunkGenData: BiomeDefinitionChunkGenData^,
            % GameRulesChangedPacketData: GameRulesChangedPacketData,
            % LevelSettings: LevelSettings^,
        ] in crate::version::v844::types,
        enums: [
            % ActorFlags: ActorFlags,
            % LevelSoundEventType: LevelSoundEventType,
            % ParticleType: ParticleType,
        ] in crate::version::v844::enums,
    },
    (859, "r/21_u12", "1.21.120"): {
        packets: [
            + GraphicsParameterOverridePacket: GraphicsParameterOverridePacket,
            % AnimatePacket: AnimatePacket^,
            % ShowStoreOfferPacket: ShowStoreOfferPacket^,
        ] in crate::version::v859::packets,
        types: [
            + BiomeReplacementData: BiomeReplacementData,
            % BiomeDefinitionChunkGenData: BiomeDefinitionChunkGenData^,
            % CameraInstruction: CameraInstruction^,
            % DebugShape: DebugShape^,
        ] in crate::version::v859::types,
        enums: [
            + CameraSplineType: CameraSplineType,
            % ActorEvent: ActorEvent,
            % ActorFlags: ActorFlags,
        ] in crate::version::v859::enums,
    },
    (898, "r/21_u13", "1.21.130"): {
        packets: [
            + ClientBoundDataStorePacket: ClientBoundDataStorePacket,
            + ServerBoundDataStorePacket: ServerBoundDataStorePacket,
            % AnimatePacket: AnimatePacket^,
            % AvailableCommandsPacket: AvailableCommandsPacket,
            % CommandOutputPacket: CommandOutputPacket^,
            % CommandRequestPacket: CommandRequestPacket^,
            % InteractPacket: InteractPacket^,
            % LegacyTelemetryEventPacket: LegacyTelemetryEventPacket^,
            % MobEffectPacket: MobEffectPacket^,
            % ResourcePackStackPacket: ResourcePackStackPacket^,
            % StartGamePacket: StartGamePacket^,
            % TextPacket: TextPacket^,
        ] in crate::version::v898::packets,
        types: [
            % CameraAimAssistCategory: CameraAimAssistCategory^,
            % CameraAimAssistPresetDefinition: CameraAimAssistPresetDefinition^,
            % CommandOriginData: CommandOriginData^,
        ] in crate::version::v898::types,
        enums: [
            % ActorEvent: ActorEvent,
            % CommandOriginType: CommandOriginType,
            % CommandOutputType: CommandOutputType,
            % LevelSoundEventType: LevelSoundEventType,
            % TextPacketType: TextPacketType,
        ] in crate::version::v898::enums,
    },
    (924, "r/26_u0", "1.26.0"): {
        packets: [
            + CameraAimAssistActorPriorityPacket: CameraAimAssistActorPriorityPacket,
            + CameraSplinePacket: CameraSplinePacket^,
            + ClientBoundDataDrivenUICloseAllScreensPacket: ClientBoundDataDrivenUICloseAllScreensPacket,
            + ClientBoundDataDrivenUIReloadPacket: ClientBoundDataDrivenUIReloadPacket,
            + ClientBoundDataDrivenUIShowScreenPacket: ClientBoundDataDrivenUIShowScreenPacket,
            + ClientBoundTextureShiftPacket: ClientBoundTextureShiftPacket,
            + VoxelShapesPacket: VoxelShapesPacket,
            % BookEditPacket: BookEditPacket^,
            % ClientBoundDataStorePacket: ClientBoundDataStorePacket,
            % GraphicsParameterOverridePacket: GraphicsParameterOverridePacket,
            % ServerBoundDataStorePacket: ServerBoundDataStorePacket,
            % ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            % StartGamePacket: StartGamePacket^,
        ] in crate::version::v924::packets,
        types: [
            + CameraSplineInstruction: CameraSplineInstruction^,
            % BiomeDefinitionChunkGenData: BiomeDefinitionChunkGenData^,
            % CameraAimAssistCategory: CameraAimAssistCategory^,
            % CameraAimAssistPresetDefinition: CameraAimAssistPresetDefinition^,
            % CameraInstruction: CameraInstruction^,
            % DebugShape: DebugShape^,
            % LevelSettings: LevelSettings^,
        ] in crate::version::v924::types,
        enums: [
            + CameraSplineEaseType: CameraSplineEaseType,
            % ActorDataIDs: ActorDataIDs,
            % BookEditAction: BookEditAction,
            % LevelSoundEventType: LevelSoundEventType,
            % TextPacketType: TextPacketType,
        ] in crate::version::v924::enums,
    },
    (944, "r/26_u1", "1.26.10"): {
        packets: [
            + ClientBoundAttributeLayerSyncPacket: ClientBoundAttributeLayerSyncPacket,
            + ClientBoundDataDrivenUICloseScreenPacket: ClientBoundDataDrivenUICloseScreenPacket,
            + LocatorBarPacket: LocatorBarPacket,
            + PartyChangedPacket: PartyChangedPacket,
            + ResourcePacksReadyForValidationPacket: ResourcePacksReadyForValidationPacket,
            + ServerBoundDataDrivenClosedPacket: ServerBoundDataDrivenClosedPacket,
            + SyncWorldClocksPacket: SyncWorldClocksPacket,
            % ClientBoundDataDrivenUIShowScreenPacket: ClientBoundDataDrivenUIShowScreenPacket,
            % GraphicsParameterOverridePacket: GraphicsParameterOverridePacket,
            % StartGamePacket: StartGamePacket^,
            % UpdateClientInputLocksPacket: UpdateClientInputLocksPacket,
            % VoxelShapesPacket: VoxelShapesPacket,
            - ClientBoundDataDrivenUICloseAllScreensPacket
        ] in crate::version::v944::packets,
        types: [
            % CameraSplineInstruction: CameraSplineInstruction^,
            % NetworkBlockPosition: NetworkBlockPosition,
            % PackedItemUseLegacyInventoryTransaction: PackedItemUseLegacyInventoryTransaction^,
        ] in crate::version::v944::types,
        enums: [
            % ContainerEnumName: ContainerEnumName,
            % LevelSoundEventType: LevelSoundEventType,
            % ParticleType: ParticleType,
        ] in crate::version::v944::enums,
    },
    (975, "r/26_u2", "1.26.20"): {
        packets: [
            + ServerPresenceInfoPacket: ServerPresenceInfoPacket,
            + ServerStoreInfoPacket: ServerStoreInfoPacket,
            % ActorEventPacket: ActorEventPacket^,
            % GraphicsParameterOverridePacket: GraphicsParameterOverridePacket,
            % InventorySlotPacket: InventorySlotPacket^,
            % LevelSoundEventPacket: LevelSoundEventPacket^,
            % LocatorBarPacket: LocatorBarPacket,
            % MobEquipmentPacket: MobEquipmentPacket^,
            % MovementPredictionSyncPacket: MovementPredictionSyncPacket^,
            % PartyChangedPacket: PartyChangedPacket,
            % PlaySoundPacket: PlaySoundPacket^,
            % ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            % UpdateClientOptionsPacket: UpdateClientOptionsPacket,
        ] in crate::version::v975::packets,
        types: [
            + BiomeNoiseGradientSurfaceData: BiomeNoiseGradientSurfaceData,
            + BiomeSurfaceBuilderData: BiomeSurfaceBuilderData^,
            + NetworkItemStackDescriptorV2: NetworkItemStackDescriptorV2,
            % BiomeDefinitionChunkGenData: BiomeDefinitionChunkGenData^,
            % DebugShape: DebugShape^,
            % DimensionDefinitionGroup: DimensionDefinitionGroup,
        ] in crate::version::v975::types,
        enums: [
            % ActorEvent: ActorEvent,
            % ActorFlags: ActorFlags,
            % LevelSoundEventType: LevelSoundEventType,
        ] in crate::version::v975::enums,
    },
    (1001, "r/26_u3", "1.26.30"): {
        packets: [
            + ClientBoundUpdateSoundDataPacket: ClientBoundUpdateSoundDataPacket,
            + PartyDestinationCookieResponsePacket: PartyDestinationCookieResponsePacket,
            + SendPartyDestinationCookiePacket: SendPartyDestinationCookiePacket,
            % BossEventPacket: BossEventPacket^,
            % ClientBoundAttributeLayerSyncPacket: ClientBoundAttributeLayerSyncPacket,
            % ClientCacheBlobStatusPacket: ClientCacheBlobStatusPacket,
            % GraphicsParameterOverridePacket: GraphicsParameterOverridePacket,
            % InventoryContentPacket: InventoryContentPacket^,
            % InventoryTransactionPacket: InventoryTransactionPacket^,
            % LevelSoundEventPacket: LevelSoundEventPacket,
            % MobArmorEquipmentPacket: MobArmorEquipmentPacket^,
            % ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            % ServerPresenceInfoPacket: ServerPresenceInfoPacket,
            % StartGamePacket: StartGamePacket^,
            % SubChunkRequestPacket: SubChunkRequestPacket^,
        ] in crate::version::v1001::packets,
        types: [
            % BiomeNoiseGradientSurfaceData: BiomeNoiseGradientSurfaceData,
            % DebugShape: DebugShape^,
            % InventoryAction: InventoryAction^,
            % LevelSettings: LevelSettings^,
        ] in crate::version::v1001::types,
        enums: [
            % ConnectionFailReason: ConnectionFailReason,
            % LevelSoundEventType: LevelSoundEventType,
            % MovementEffectType: MovementEffectType,
        ] in crate::version::v1001::enums,
    },
    (2168, "r/26_u4", "1.26.40"): {
        packets: [
            % AnvilDamagePacket: AnvilDamagePacket^,
            % ClientBoundMapItemDataPacket: ClientBoundMapItemDataPacket^,
            % ClientBoundUpdateSoundDataPacket: ClientBoundUpdateSoundDataPacket^,
            % CraftingDataPacket: CraftingDataPacket^,
            % CreativeContentPacket: CreativeContentPacket^,
            % LevelChunkPacket: LevelChunkPacket^,
            % MovePlayerPacket: MovePlayerPacket^,
            % PlaySoundPacket: PlaySoundPacket^,
            % PlayerAuthInputPacket: PlayerAuthInputPacket^,
            % PlayerListPacket: PlayerListPacket^,
            % PlayerLocationPacket: PlayerLocationPacket,
            % PlayerSkinPacket: PlayerSkinPacket^,
            % PlayerUpdateEntityOverridesPacket: PlayerUpdateEntityOverridesPacket^,
            % ResourcePackClientResponsePacket: ResourcePackClientResponsePacket,
            % ResourcePacksInfoPacket: ResourcePacksInfoPacket,
            % ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            % ServerPresenceInfoPacket: ServerPresenceInfoPacket,
            % SetScorePacket: SetScorePacket^,
            % SetScoreboardIdentityPacket: SetScoreboardIdentityPacket^,
            % StartGamePacket: StartGamePacket^,
            % SubChunkPacket: SubChunkPacket^,
            % TransferPlayerPacket: TransferPlayerPacket^,
        ] in crate::version::v2168::packets,
        types: [
            + CraftingRecipeIngredient: CraftingRecipeIngredient,
            + GatheringsConfig: GatheringsConfig,
            + ItemStackRequestNetworkItemInstanceDescriptor: ItemStackRequestNetworkItemInstanceDescriptor^,
            + MovePlayerTeleportData: MovePlayerTeleportData,
            + MultiRecipe: MultiRecipe,
            + RedactableString: RedactableString,
            + SoundData: SoundData,
            % DimensionDefinitionGroup: DimensionDefinitionGroup,
            % ItemStackRequestSlotInfo: ItemStackRequestSlotInfo^,
            % ItemStackResponseInfo: ItemStackResponseInfo^,
            % ItemStackResponseSlotInfo: ItemStackResponseSlotInfo^,
            % LevelSettings: LevelSettings^,
            % MapDecoration: MapDecoration,
            % MapItemTrackedActorUniqueID: MapItemTrackedActorUniqueID^,
            % MoveActorDeltaData: MoveActorDeltaData^,
            % NetworkItemInstanceDescriptor: NetworkItemInstanceDescriptor,
            % NetworkItemStackDescriptor: NetworkItemStackDescriptor,
            % NetworkItemStackDescriptorV2: NetworkItemStackDescriptorV2,
            % PlayerBlockActionData: PlayerBlockActionData^,
            % RecipeIngredient: RecipeIngredient^,
            % RecipeUnlockingRequirement: RecipeUnlockingRequirement^,
            % SerializedSkin: SerializedSkin^,
            % ShapedRecipe: ShapedRecipe^,
            % ShapelessRecipe: ShapelessRecipe^,
            % SmithingTransformRecipe: SmithingTransformRecipe^,
            % SmithingTrimRecipe: SmithingTrimRecipe^,
            % StructureEditorData: StructureEditorData^,
            % SubChunkPos: SubChunkPos,
        ] in crate::version::v2168::types,
        enums: [
            + ArmSizeType: ArmSizeType,
            + PersonaPieceType: PersonaPieceType,
            + PlayerAuthInputData: PlayerAuthInputData,
            % ActorFlags: ActorFlags,
            % AnimatedTextureType: AnimatedTextureType,
            % AnimationExpression: AnimationExpression,
            % DataItemType: DataItemType^,
            % EducationEditionOffer: EducationEditionOffer,
            % ItemDescriptorType: ItemDescriptorType,
            % ItemStackNetResult: ItemStackNetResult,
            % ItemStackRequestActionType: ItemStackRequestActionType^,
            % LevelSoundEventType: LevelSoundEventType,
            % NewInteractionModel: NewInteractionModel,
            % ParticleType: ParticleType,
            % PlayerPositionMode: PlayerPositionMode,
            % StructureRedstoneSaveMode: StructureRedstoneSaveMode,
        ] in crate::version::v2168::enums,
    },
    (2169, "r/26_u4_hotfix5", "1.26.45"): {},
    (2193, "r/26_u5", "1.26.50"): {
        packets: [
            + RecordStartedPacket: RecordStartedPacket^,
            + SetPlayerFurnaceOptionsPacket: SetPlayerFurnaceOptionsPacket,
            % BossEventPacket: BossEventPacket^,
            % ClientBoundUpdateSoundDataPacket: ClientBoundUpdateSoundDataPacket^,
            % InventoryTransactionPacket: InventoryTransactionPacket^,
            % PlaySoundPacket: PlaySoundPacket^,
            % PlayerAuthInputPacket: PlayerAuthInputPacket^,
            % ServerBoundDiagnosticsPacket: ServerBoundDiagnosticsPacket,
            % ServerBoundPackSettingChangePacket: ServerBoundPackSettingChangePacket,
            % SubChunkPacket: SubChunkPacket^,
        ] in crate::version::v2193::packets,
        types: [
            % CameraPreset: CameraPreset^,
            % DebugShape: DebugShape^,
            % DimensionDefinitionGroup: DimensionDefinitionGroup,
            % ItemStackResponseInfo: ItemStackResponseInfo^,
            % ItemStackResponseSlotInfo: ItemStackResponseSlotInfo^,
            % MoveActorDeltaData: MoveActorDeltaData^,
            % PackedItemUseLegacyInventoryTransaction: PackedItemUseLegacyInventoryTransaction^,
        ] in crate::version::v2193::types,
        enums: [
            % ConnectionFailReason: ConnectionFailReason,
            % PersonaPieceType: PersonaPieceType,
        ] in crate::version::v2193::enums,
    }
];