pub mod base_game_version;
pub mod chat_restriction_level;
pub mod connection_request;
pub mod edu_shared_uri_resource;
pub mod experiments;
pub mod gamerule;
pub mod level_settings;
pub mod network_block_pos;
pub mod network_permissions;
pub mod pack_info_behavior;
pub mod pack_info_resource;
pub mod pack_url;
pub mod play_status;
pub mod player_movement_mode;
pub mod player_movement_settings;
pub mod resource_packs_response_status;
pub mod resource_packs_stack_pack;
pub mod spawn_biome_type;
pub mod spawn_settings;
pub mod interact_action;
pub mod input_data;
pub mod input_mode;
pub mod play_mode;
pub mod interaction_model;
mod block_action;
mod inventory_transaction;
